// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _reconfigureMessage =
      'you can reconfigure this by running the FlutterFire CLI again.';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        '$_reconfigureMessage',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          '$_reconfigureMessage',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          '$_reconfigureMessage',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          '$_reconfigureMessage',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDGjxgLjoRRRRRbg3tta-8kx3GqgphhHrQ',
      appId: '1:992879245046:android:22ef480bfbe53cdbf1ded7',
      messagingSenderId: '992879245046',
      projectId: 'licensedxb---patrol-app',
      storageBucket: "licensedxb---patrol-app.appspot.com");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDtmShENw7blPgvKNSSccSz1FFXhybY4Do',
      appId: '1:992879245046:ios:646b6fd8caaac08ef1ded7',
      messagingSenderId: '992879245046',
      projectId: 'licensedxb---patrol-app',
      iosBundleId: 'com.licensedxb.patroluae',
      storageBucket: "licensedxb---patrol-app.appspot.com");
}
